/**
 * autoTaskGenerationService.js
 *
 * Converts active AutoTaskTemplate documents into real Task documents.
 * Generated tasks are identical to manually-created tasks — same collection,
 * same APIs, same Flutter/web flows — with three extra read-only tracking fields:
 *   isAutoGenerated, autoTaskTemplateId, generatedForDate
 *
 * Called by the hourly cron job (autoTaskCron.js) and the /generate-now endpoint.
 */

import mongoose from 'mongoose';
import Task            from '../model/Task.js';
import AutoTaskTemplate from '../model/AutoTaskTemplate.js';
import Admin           from '../model/Admin.js';
import Employee        from '../model/Employee.js';
import User            from '../model/User.js';
import Branch          from '../model/Branch.js';
import { getAccessibleStoreIds } from '../lib/permissions.js';
import { sendNotification }      from '../utils/notificationHelper.js';

// ─────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────

/** Returns today's date as YYYY-MM-DD in local server time */
const todayStr = () => {
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm   = String(d.getMonth() + 1).padStart(2, '0');
  const dd   = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
};

/** Parse a YYYY-MM-DD string into a Date at midnight UTC */
const parseDate = (str) => {
  if (!str || typeof str !== 'string') return null;
  const trimmed = str.trim();
  if (!trimmed || trimmed === 'null' || trimmed === 'undefined' || trimmed === 'NaN-NaN-NaN') return null;
  const parts = trimmed.split('-');
  if (parts.length !== 3) return null;
  const [y, m, d] = parts.map(Number);
  if (isNaN(y) || isNaN(m) || isNaN(d)) return null;
  const date = new Date(y, m - 1, d);
  return isNaN(date.getTime()) ? null : date;
};

/**
 * Determines whether a template should generate tasks on `targetDate`.
 * @param {AutoTaskTemplate} template
 * @param {string} targetDate — YYYY-MM-DD
 * @returns {boolean}
 */
const shouldGenerateToday = (template, targetDate) => {
  const target = parseDate(targetDate);
  const start  = parseDate(template.startDate);
  const end    = parseDate(template.endDate);

  if (!target || !start) return false;

  // Must be on or after start date
  if (target < start) return false;

  // Must be before or on end date (if set)
  if (end) {
    // Compare date-only (ignore time)
    const endMidnight = new Date(end.getFullYear(), end.getMonth(), end.getDate(), 23, 59, 59);
    if (target > endMidnight) return false;
  }

  const type = template.repeatType;

  if (type === 'daily' || type === 'custom') {
    return true; // every day
  }

  if (type === 'weekly') {
    // Same day of the week as startDate
    return target.getDay() === start.getDay();
  }

  if (type === 'monthly') {
    // Same day of the month as startDate
    return target.getDate() === start.getDate();
  }

  return false;
};

/** Simple sequential task code generator (mirrors TaskController.nextTaskCode) */
const nextTaskCode = async () => {
  const count = await Task.countDocuments();
  return `TSK-${String(count + 1).padStart(3, '0')}`;
};

/** Resolve store name + code from an Admin or User document */
const resolveStore = async (assigneeId) => {
  try {
    const admin = await Admin.findById(assigneeId).populate('branches');
    if (admin) {
      if (['super_admin', 'admin', 'hr_admin'].includes(admin.role)) {
        return { storeName: 'Office', storeCode: '' };
      }
      const branch = admin.branches?.[0];
      return {
        storeName: branch?.workingBranch || '',
        storeCode: branch?.locCode ? `Z-${branch.locCode}` : '',
      };
    }
    const user = await User.findById(assigneeId);
    if (user) {
      return {
        storeName: user.workingBranch || '',
        storeCode: user.locCode
          ? (Array.isArray(user.locCode) ? `Z-${user.locCode[0]}` : `Z-${user.locCode}`)
          : '',
      };
    }
  } catch (_) {}
  return { storeName: '', storeCode: '' };
};

// ─────────────────────────────────────────────────────────────────
// Assignee Resolution
// (Mirrors the logic in TaskController.createTask for group modes)
// ─────────────────────────────────────────────────────────────────

/**
 * Resolves a template's assignMode + selections into a flat list of
 * { id, label } objects — one entry per individual task to be created.
 *
 * @param {AutoTaskTemplate} template
 * @param {Admin} creator — the Admin document of the template creator
 * @returns {Array<{id: string, label: string}>}
 */
const resolveAssignees = async (template, creator) => {
  const { assignMode, selectedStores, selectedRoles, selectedUsers } = template;
  const targets = [];

  // ── all_employees ──────────────────────────────────────────────
  if (assignMode === 'all_employees') {
    const storeIds   = await getAccessibleStoreIds(creator._id);
    const dbEmployees = await Employee.find({
      storeId: { $in: storeIds },
      status:  'Active',
    }).populate('storeId');

    const branches   = await Branch.find({ _id: { $in: storeIds } });
    const locCodes   = branches.map(b => b.locCode);
    const users      = await User.find({ locCode: { $in: locCodes } }).lean();

    dbEmployees.forEach(emp => {
      const name  = emp.firstName ? `${emp.firstName} ${emp.lastName || ''}`.trim() : (emp.username || 'Employee');
      const desig = emp.designation || 'Staff';
      const store = (emp.storeId && emp.storeId.workingBranch) || emp.workingBranch || 'Store';
      targets.push({ id: emp._id.toString(), label: `${name} - ${desig} - ${store}` });
    });

    users.forEach(u => {
      if (!targets.some(t => t.id === u._id.toString())) {
        targets.push({
          id:    u._id.toString(),
          label: `${u.username || 'Employee'} - ${u.designation || 'Staff'} - ${u.workingBranch || 'Store'}`,
        });
      }
    });
    return targets;
  }

  // ── store ──────────────────────────────────────────────────────
  if (assignMode === 'store' && selectedStores?.length) {
    // Fetch all accessible employees then filter by store name
    const storeIds    = await getAccessibleStoreIds(creator._id);
    const dbEmployees = await Employee.find({
      storeId: { $in: storeIds },
      status:  'Active',
    }).populate('storeId');

    const branches  = await Branch.find({ _id: { $in: storeIds } });
    const locCodes  = branches.map(b => b.locCode);
    const users     = await User.find({ locCode: { $in: locCodes } }).lean();

    // Normalize selected store names for comparison
    const storeSet = new Set(selectedStores.map(s => s.toLowerCase().trim()));

    dbEmployees.forEach(emp => {
      const empStore = ((emp.storeId && emp.storeId.workingBranch) || emp.workingBranch || '').toLowerCase().trim();
      if (storeSet.has(empStore)) {
        const name  = emp.firstName ? `${emp.firstName} ${emp.lastName || ''}`.trim() : (emp.username || 'Employee');
        const desig = emp.designation || 'Staff';
        const store = (emp.storeId && emp.storeId.workingBranch) || emp.workingBranch || 'Store';
        targets.push({ id: emp._id.toString(), label: `${name} - ${desig} - ${store}` });
      }
    });

    users.forEach(u => {
      const empStore = (u.workingBranch || '').toLowerCase().trim();
      if (storeSet.has(empStore) && !targets.some(t => t.id === u._id.toString())) {
        targets.push({
          id:    u._id.toString(),
          label: `${u.username || 'Employee'} - ${u.designation || 'Staff'} - ${u.workingBranch || 'Store'}`,
        });
      }
    });
    return targets;
  }

  // ── role ───────────────────────────────────────────────────────
  if (assignMode === 'role' && selectedRoles?.length) {
    const roleSet = new Set(selectedRoles.map(r => r.toLowerCase()));
    // Map UI role keys to Admin.role values
    const adminRoles = [];
    const includeStaff = roleSet.has('employee') || roleSet.has('staff');
    if (roleSet.has('super_admin'))   adminRoles.push('super_admin');
    if (roleSet.has('admin'))         adminRoles.push('admin');
    if (roleSet.has('hr_admin'))      adminRoles.push('hr_admin');
    if (roleSet.has('cluster_admin')) adminRoles.push('cluster_admin');
    if (roleSet.has('store_admin'))   adminRoles.push('store_admin');

    if (adminRoles.length) {
      const storeIds = await getAccessibleStoreIds(creator._id);
      let adminQuery = { role: { $in: adminRoles }, isActive: true };

      // Cluster/Store admins: scope to accessible stores
      if (!['super_admin', 'admin', 'hr_admin'].includes(creator.role)) {
        adminQuery.branches = { $in: storeIds };
      }
      const admins = await Admin.find(adminQuery).populate('branches');
      admins.forEach(ad => {
        const desig = ad.subRole && ad.subRole !== 'NR' ? ad.subRole : ad.role;
        const store = (ad.role === 'super_admin' || ad.role === 'admin' || ad.role === 'hr_admin')
          ? 'Office'
          : (ad.branches?.[0]?.workingBranch || 'Store');
        targets.push({ id: ad._id.toString(), label: `${ad.name} - ${desig} - ${store}` });
      });
    }

    if (includeStaff) {
      const storeIds    = await getAccessibleStoreIds(creator._id);
      const dbEmployees = await Employee.find({
        storeId: { $in: storeIds },
        status:  'Active',
      }).populate('storeId');

      const branches = await Branch.find({ _id: { $in: storeIds } });
      const locCodes = branches.map(b => b.locCode);
      const users    = await User.find({ locCode: { $in: locCodes } }).lean();

      dbEmployees.forEach(emp => {
        if (!targets.some(t => t.id === emp._id.toString())) {
          const name  = emp.firstName ? `${emp.firstName} ${emp.lastName || ''}`.trim() : (emp.username || 'Employee');
          const desig = emp.designation || 'Staff';
          const store = (emp.storeId && emp.storeId.workingBranch) || emp.workingBranch || 'Store';
          targets.push({ id: emp._id.toString(), label: `${name} - ${desig} - ${store}` });
        }
      });
      users.forEach(u => {
        if (!targets.some(t => t.id === u._id.toString())) {
          targets.push({
            id:    u._id.toString(),
            label: `${u.username || 'Employee'} - ${u.designation || 'Staff'} - ${u.workingBranch || 'Store'}`,
          });
        }
      });
    }
    return targets;
  }

  // ── individual ─────────────────────────────────────────────────
  if (assignMode === 'individual' && selectedUsers?.length) {
    return selectedUsers.map(u => ({ id: u.id, label: u.label }));
  }

  return targets;
};

// ─────────────────────────────────────────────────────────────────
// Main Generation Function
// ─────────────────────────────────────────────────────────────────

/**
 * Generates tasks for all active AutoTaskTemplates that are due on `targetDate`.
 *
 * @param {string} [targetDate] — YYYY-MM-DD, defaults to today
 * @param {string} [specificTemplateId] — if set, only generate for this template
 * @returns {Promise<{ generated: number, skipped: number, errors: number }>}
 */
export const generateAutoTasks = async (targetDate = null, specificTemplateId = null) => {
  const dateStr = targetDate || todayStr();
  let generated = 0;
  let skipped   = 0;
  let errors    = 0;

  try {
    // Fetch templates to process
    const query = { isActive: true };
    if (specificTemplateId) {
      query._id = new mongoose.Types.ObjectId(specificTemplateId);
    }
    const templates = await AutoTaskTemplate.find(query).lean();

    for (const tmpl of templates) {
      // For generate-now (specificTemplateId set) skip the schedule check
      if (!specificTemplateId && !shouldGenerateToday(tmpl, dateStr)) {
        continue;
      }

      // Respect endDate even for generate-now
      if (tmpl.endDate) {
        const end    = parseDate(tmpl.endDate);
        const target = parseDate(dateStr);
        if (end && target > end) {
          console.log(`⏭  AutoTask [${tmpl._id}] "${tmpl.title}" — past end date, skipping`);
          skipped++;
          continue;
        }
      }

      // Resolve creator
      let creator;
      try {
        creator = await Admin.findById(tmpl.createdBy).populate('branches');
        if (!creator) {
          console.warn(`⚠️  AutoTask [${tmpl._id}] creator not found — skipping`);
          skipped++;
          continue;
        }
      } catch (err) {
        console.error(`❌  AutoTask [${tmpl._id}] error fetching creator:`, err.message);
        errors++;
        continue;
      }

      // Resolve all assignees
      let assignees = [];
      try {
        assignees = await resolveAssignees(tmpl, creator);
      } catch (err) {
        console.error(`❌  AutoTask [${tmpl._id}] error resolving assignees:`, err.message);
        errors++;
        continue;
      }

      if (assignees.length === 0) {
        console.warn(`⚠️  AutoTask [${tmpl._id}] no assignees resolved — skipping`);
        skipped++;
        continue;
      }

      const creatorName = creator.name;
      const roleLabels  = {
        super_admin: 'Super Admin', admin: 'Admin', hr_admin: 'HR Admin',
        cluster_admin: 'Cluster Admin', store_admin: 'Store Admin',
      };
      const roleLabel = roleLabels[creator.role] || creator.role;
      const subRole   = creator.subRole && creator.subRole !== 'NR' ? creator.subRole : '';
      const assignedByRole = subRole ? `${roleLabel} · ${subRole}` : roleLabel;

      for (const assignee of assignees) {
        // ── Duplicate prevention ───────────────────────────────────────
        const existing = await Task.findOne({
          autoTaskTemplateId: tmpl._id,
          generatedForDate:   dateStr,
          assignedTo:         assignee.id,
        });

        if (existing) {
          skipped++;
          continue;
        }

        // ── Resolve store details for this assignee ───────────────────
        const { storeName, storeCode } = await resolveStore(assignee.id);

        // ── Create the Task (identical to manual task creation) ───────
        try {
          const taskCode = await nextTaskCode();
          const task = await Task.create({
            taskCode,
            title:        tmpl.title.trim(),
            category:     tmpl.category.trim(),
            subCategory:  tmpl.subCategory.trim(),
            assignedTo:   assignee.id,
            assignedToLabel: assignee.label,
            mode: 'auto',
            startDate:    dateStr,
            startTime:    tmpl.startTime || '',
            endDate:      dateStr,            // tasks are for a single day
            endTime:      tmpl.endTime || tmpl.startTime || '',
            description:  tmpl.description || '',
            priority:     tmpl.priority,
            status:       'PENDING',
            storeName,
            storeCode,
            createdBy:    creator._id,
            assignedByName:  creatorName,
            assignedByRole,
            attachment:      tmpl.attachment     || '',
            attachmentName:  tmpl.attachmentName || '',
            workMap: [{
              assignedTo:      assignee.id,
              assignedToLabel: assignee.label,
              assignedBy:      creatorName,
              assignedAt:      new Date(),
              action:          'ASSIGNED',
            }],
            // Tracking fields
            isAutoGenerated:    true,
            autoTaskTemplateId: tmpl._id,
            generatedForDate:   dateStr,
          });

          // ── Send notification (same as manual) ──────────────────────
          await sendNotification({
            title:      'New Task Assigned',
            body:       `You have been assigned a new task: "${tmpl.title.trim()}" by ${creatorName}`,
            userIds:    [assignee.id],
            senderName: creatorName,
            category:   'Task',
          });

          generated++;
          console.log(`✅  AutoTask [${tmpl._id}] → Task ${task.taskCode} for ${assignee.label}`);
        } catch (err) {
          console.error(`❌  AutoTask [${tmpl._id}] error creating task for ${assignee.id}:`, err.message);
          errors++;
        }
      }
    }
  } catch (err) {
    console.error('❌  generateAutoTasks fatal error:', err);
    errors++;
  }

  console.log(`📊  Auto Task Generation [${dateStr}]: generated=${generated}, skipped=${skipped}, errors=${errors}`);
  return { generated, skipped, errors };
};
