import mongoose from 'mongoose';

const taskSchema = new mongoose.Schema({
  taskCode: { type: String, unique: true, index: true },
  title: { type: String, required: true, trim: true },
  category: { type: String, required: true, trim: true },
  subCategory: { type: String, required: true, trim: true },
  adminTitle: { type: String, trim: true },
  adminCategory: { type: String, trim: true },
  adminSubCategory: { type: String, trim: true },
  assignedTo: { type: String, required: true, trim: true },
  assignedToLabel: { type: String, trim: true },
  mode: { type: String, enum: ['task', 'auto'], default: 'task' },
  startDate: { type: String, required: true },
  startTime: { type: String, default: '' },
  endDate: { type: String, default: '' },
  endTime: { type: String, default: '' },
  description: { type: String, default: '' },
  additionalInfo: { type: String, default: '' },
  priority: { type: String, required: true, trim: true },
  status: {
    type: String,
    enum: ['PENDING', 'IN PROGRESS', 'COMPLETED', 'OVERDUE', 'ON HOLD', 'UNDER REVIEW', 'REASSIGNED', 'EXTENSION REQUESTED'],
    default: 'IN PROGRESS',
  },
  requestedExtensionDate: { type: String, default: '' },
  previousStatus: { type: String, default: '' },
  reassignedCategory: { type: String, default: '' },
  reassignedSubCategory: { type: String, default: '' },
  storeName: { type: String, default: '' },
  storeCode: { type: String, default: '', index: true },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'Admin', required: true },
  assignedByName: { type: String, default: '' },
  assignedByRole: { type: String, default: '' },
  attachment: { type: String, default: '' },
  attachmentName: { type: String, default: '' },
  reviewAttachment: { type: String, default: '' },
  reviewAttachmentName: { type: String, default: '' },
  attachments: [{
    name: { type: String },
    file: { type: String }, // Base64 data string
    uploadedBy: { type: String },
    uploadedByName: { type: String },
    uploadedAt: { type: Date, default: Date.now },
    step: { type: String } // 'ASSIGNED', 'REASSIGNED', or 'UNDER REVIEW'
  }],
  workMap: [{
    assignedTo: { type: String },
    assignedToLabel: { type: String },
    assignedBy: { type: String },
    assignedAt: { type: Date, default: Date.now },
    action: { type: String, enum: ['ASSIGNED', 'REASSIGNED', 'COMPLETED', 'UNDER REVIEW', 'IN PROGRESS', 'ON HOLD', 'EXTENSION REQUESTED', 'EXTENSION APPROVED', 'EXTENSION REJECTED'], default: 'ASSIGNED' },
    details: { type: String, default: '' }
  }],

  // Auto-task tracking — set by the generation service, not by manual task creation
  isAutoGenerated:    { type: Boolean, default: false },
  autoTaskTemplateId: { type: mongoose.Schema.Types.ObjectId, ref: 'AutoTaskTemplate', default: null },
  generatedForDate:   { type: String, default: '' },  // YYYY-MM-DD
}, { timestamps: true });

taskSchema.index({ createdAt: -1 });
taskSchema.index({ category: 1 });
taskSchema.index({ priority: 1 });
taskSchema.index({ status: 1 });
taskSchema.index({ assignedTo: 1 });
taskSchema.index({ createdBy: 1 });
// Compound index for auto-task duplicate prevention
taskSchema.index({ autoTaskTemplateId: 1, generatedForDate: 1, assignedTo: 1 }, { sparse: true });

const Task = mongoose.model('Task', taskSchema);
export default Task;
